title: Soteria
author: Marc Goulding Tojar
email: gouldingmarc@gmail.com
description: Safety
github_username: MarcGoulding
# linkedin: https://www.linkedin.com/in/marc-goulding
baseurl: /fund

# Build settings
theme: minima
